### ISSUE TITLE
MMT+ 不加后处理的在visda2020 验证集上的性能

### ISSUE THREAD

**Issue by jjn037** [yxgeee/VisDA-ECCV20#1]
hello，恭喜大佬获得第二名，感觉后处理在加一些方法能直奔第一。一直关注你们MMT和无监督reid的工作，看了你们比赛的report，好奇MMT+不加后处理的在visda2020 验证集上的性能是多少，还有记录吗？

**Comment by yxgeee** [comment]
你好，首先谢谢。关于不加后处理的结果，当backbone为resnet50-ibn-a时，在val上结果为（mAP为top-100的mAP，为了和leaderboard保持一致）：
```
Mean AP: 63.8%
CMC Scores:
  top-1          82.5%
  top-5          89.7%
  top-10         93.6%
```
其他backbone的话，可以根据README里提供的下载链接进行下载，然后根据如下命令进行无后处理的测试：
```
python -u examples/test.py -d target_val --dsbn -a ${ARCH} --resume ${MODEL}
```
