### ISSUE TITLE
Why do you use BCE loss in this formula in your paper?

### ISSUE THREAD

**Issue by zhoufengfan** [yxgeee/VisDA-ECCV20#2]
![image](https://user-images.githubusercontent.com/67182587/104309736-981e7200-550d-11eb-85f8-a2d9a286d3b3.png)
![image](https://user-images.githubusercontent.com/67182587/104309760-a1a7da00-550d-11eb-9694-af972adf5ba9.png)

Thanks.

**Comment by yxgeee** [comment]
Since the traditional form of triplet loss cannot support soft-label training. With such BCE loss, we can change the label "1" to soft labels within [0,1] to support soft-label training. Please see the paper of MMT for details.
